# reporter.py
# Formats audit findings into a structured plain-text report and saves
# it to the output directory. This is the only module that writes files.

import os
from datetime import datetime

import config
from utils.logger import masLog

def generate_report(source: str, findings: list) -> str:
    """
    Build a plain-text audit report and save it to the output directory.

    Parameters:
        source (str): The URL or file path that was audited.
        findings (list): Combined list of all finding dictionaries from all checks.

    Returns:
        str: The full file path of the saved report.
    """

    masLog(f"Generating report for: {source}")

    # Build the report as a list of lines, then join them at the end.
    # This is cleaner than string concatenation and easier to maintain.
    lines = []

    # --- Header ---
    lines.append(config.REPORT_SEPARATOR)
    lines.append(f"{config.TOOL_NAME} v{config.TOOL_VERSION}")
    lines.append(f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Source audited:   {source}")
    lines.append(f"Total findings:   {len(findings)}")
    lines.append(config.REPORT_SEPARATOR)
    lines.append("")

    # --- Findings ---
    if not findings:
        # No issues found — report a clean pass.
        lines.append("RESULT: No accessibility issues detected by this audit.")
        lines.append("")
        lines.append("Note: This automated audit covers a defined subset of")
        lines.append("WCAG 2.1 AA criteria. Manual testing is always recommended.")
    else:
        lines.append("FINDINGS:")
        lines.append("")

        # Number each finding so the report is easy to reference.
        for i, finding in enumerate(findings, start=1):
            lines.append(f"  [{i}] {finding['check']} — WCAG {finding['wcag']} (Level {finding['level']})")
            lines.append(f"      Severity: {finding['severity'].upper()}")
            lines.append(f"      {finding['message']}")
            lines.append("")

    # --- Footer ---
    lines.append(config.REPORT_SEPARATOR)
    lines.append("SCOPE NOTE:")
    lines.append("This report was generated by the MAS Accessibility Audit Toolkit.")
    lines.append("Checks performed: alt text, heading structure, form labels, lang attribute,")
    lines.append("tabindex abuse, empty links, empty buttons, autoplay media, PDF link warnings.")
    lines.append("This is not a certification. Manual review is recommended.")
    lines.append(config.REPORT_SEPARATOR)

    # Join all lines into a single string with newlines between them.
    report_text = "\n".join(lines)

    # --- Save to output directory ---

    # Generate a timestamped filename so each run produces a unique file.
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Sanitize the source string to make it safe as a filename.
    # Replace characters that are illegal in Windows filenames with underscores.
    safe_source = source.replace("https://", "").replace("http://", "")
    for char in r'\/:*?"<>|':
        safe_source = safe_source.replace(char, "_")

    # Trim to 50 characters so filenames don't get unwieldy.
    safe_source = safe_source[:50]

    filename = f"audit_{timestamp}_{safe_source}.txt"
    filepath = os.path.join(config.OUTPUT_DIR, filename)

    # Write the report to disk.
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report_text)

    masLog(f"Report saved: {filepath}")
    return filepath